keys:
    - &laptop age17unjayw40yr0exhfrmcsznrs6ajsv6pje5h94ldgkawat9gp2deq8tnr5a
creation_rules:
    - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
      key_groups:
          - age:
                - *laptop
